server:
  port: 8083

spring:
  application:
    name: reservas-api
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    problemdetails:
      enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.universidad.reservas: INFO
