server:
  port: 8082

spring:
  application:
    name: cursos-api
  jackson:
    default-property-inclusion: non_null
  mvc:
    problemdetails:
      enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.universidad.cursos: INFO
